name: 'actions-upload-url-whitelist-to-s3'
description: 'Test'

inputs:
  sitemap_filename:
    description: 'Sitemap entry filename'
    required: true
  sitemap_basepath:
    description: 'The basepath of sitemap'
    required: true
  sitemap_baseurl:
    description: 'The baseurl of sitemap'
    required: true
  s3_bucket_name:
    description: 'Target S3 bucket'
    required: true
  output_urllist_filename:
    description: ''
    required: false
    default: 'urllist'

runs:
  using: 'node16'
  main: 'dist/index.js'
